// <auto-generated />
using System;
using CentroDeAdopcion_LaEsperanza.DB_Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CentroDeAdopcion_LaEsperanza.Migrations
{
    [DbContext(typeof(CentroDeAdopcionContext))]
    [Migration("20250120224243_AgregarCEstado")]
    partial class AgregarCEstado
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CentroDeAdopcion_LaEsperanza.Models.Adopcione", b =>
                {
                    b.Property<int>("IdAdopcion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_adopcion");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAdopcion"));

                    b.Property<DateTime?>("FechaSolicitud")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_solicitud")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("IdAdoptante")
                        .HasColumnType("int")
                        .HasColumnName("id_adoptante");

                    b.Property<int?>("IdMascota")
                        .HasColumnType("int")
                        .HasColumnName("id_mascota");

                    b.HasKey("IdAdopcion")
                        .HasName("PK__Adopcion__E4E156E9B264DB76");

                    b.HasIndex("IdAdoptante");

                    b.HasIndex("IdMascota");

                    b.ToTable("Adopciones");
                });

            modelBuilder.Entity("CentroDeAdopcion_LaEsperanza.Models.Mascota", b =>
                {
                    b.Property<int>("IdMascota")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_mascota");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMascota"));

                    b.Property<int>("Edad")
                        .HasColumnType("int")
                        .HasColumnName("edad");

                    b.Property<string>("EstadoSalud")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("estado_salud");

                    b.Property<string>("Foto")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("foto");

                    b.Property<int?>("IdPropietario")
                        .HasColumnType("int")
                        .HasColumnName("id_propietario");

                    b.Property<string>("Nombre")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nombre");

                    b.Property<string>("Raza")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("raza");

                    b.Property<string>("Sexo")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("sexo");

                    b.Property<string>("Tamaño")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("tamaño");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("tipo");

                    b.HasKey("IdMascota")
                        .HasName("PK__Mascotas__6F03735295F2FCE5");

                    b.HasIndex("IdPropietario");

                    b.ToTable("Mascotas");
                });

            modelBuilder.Entity("CentroDeAdopcion_LaEsperanza.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_usuario");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("apellido");

                    b.Property<string>("Contrasena")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("contrasena");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("direccion");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("FotoUrl")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("FotoUrl");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nombre");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("rol");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("telefono");

                    b.HasKey("IdUsuario")
                        .HasName("PK__Usuarios__4E3E04AD862941B4");

                    b.HasIndex(new[] { "Email" }, "UQ__Usuarios__AB6E61641BB4BBD8")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("CentroDeAdopcion_LaEsperanza.Models.Adopcione", b =>
                {
                    b.HasOne("CentroDeAdopcion_LaEsperanza.Models.Usuario", "IdAdoptanteNavigation")
                        .WithMany("Adopciones")
                        .HasForeignKey("IdAdoptante")
                        .HasConstraintName("FK__Adopcione__id_ad__4316F928");

                    b.HasOne("CentroDeAdopcion_LaEsperanza.Models.Mascota", "IdMascotaNavigation")
                        .WithMany("Adopciones")
                        .HasForeignKey("IdMascota")
                        .HasConstraintName("FK__Adopcione__id_ma__4222D4EF");

                    b.Navigation("IdAdoptanteNavigation");

                    b.Navigation("IdMascotaNavigation");
                });

            modelBuilder.Entity("CentroDeAdopcion_LaEsperanza.Models.Mascota", b =>
                {
                    b.HasOne("CentroDeAdopcion_LaEsperanza.Models.Usuario", "IdPropietarioNavigation")
                        .WithMany("Mascota")
                        .HasForeignKey("IdPropietario")
                        .HasConstraintName("FK__Mascotas__id_pro__3E52440B");

                    b.Navigation("IdPropietarioNavigation");
                });

            modelBuilder.Entity("CentroDeAdopcion_LaEsperanza.Models.Mascota", b =>
                {
                    b.Navigation("Adopciones");
                });

            modelBuilder.Entity("CentroDeAdopcion_LaEsperanza.Models.Usuario", b =>
                {
                    b.Navigation("Adopciones");

                    b.Navigation("Mascota");
                });
#pragma warning restore 612, 618
        }
    }
}
